Repository vagator/test-infra, pull requests merged in 2021-12, with the labels that each got.

#1 Update test.yaml
  config/jobs/test-prow/test.yaml
Labels: size/XS, lgtm

#2 Update test.yaml
  config/jobs/test-prow/test.yaml
Labels: size/XS, lgtm, approved

#3 Create presubmits.yaml
  config/test-infra/presubmits.yaml
Labels: lgtm, approved, size/S

#5 Create presubmits.yaml
  config/jobs/test-infra/presubmits.yaml
Labels: lgtm, approved, size/S

#6 Update test.yaml
  config/jobs/test-prow/test.yaml
Labels: size/XS, lgtm, approved

#8 Update plugins.yaml
  config/prow/plugins.yaml
Labels: size/XS, lgtm, approved
