Repository vagator/test-infra, pull requests merged in 2022-01, with the labels that each got.

#9 Drop periodic job
  config/jobs/test-prow/test.yaml
Labels: size/XS, lgtm, approved

#10 Update test.yaml
  config/jobs/test-prow/test.yaml
Labels: lgtm, approved, size/S

#11 Update test.yaml
  config/jobs/test-prow/test.yaml
Labels: size/XS, lgtm, approved

#12 Update test.yaml
  config/jobs/test-prow/test.yaml
Labels: size/XS, lgtm, approved

#13 Update test.yaml
  config/jobs/test-prow/test.yaml
Labels: size/XS, lgtm, approved

#14 Update test.yaml
  config/jobs/test-prow/test.yaml
Labels: size/XS, lgtm, approved

#15 Update test.yaml
  config/jobs/test-prow/test.yaml
Labels: lgtm, approved, size/S

#17 Add Christian and Karuppiah to OWNERS
  config/OWNERS
Labels: size/XS, lgtm, approved

#18 Move OWNERS to root
  OWNERS
Labels: size/XS, lgtm

#16 Add Prow job to build image from dockerfile
  config/jobs/build-images/build.yaml
  images/dind-go-kubectl/Dockerfile
  scripts/ci-docker-build-image.sh
Labels: lgtm, approved, ok-to-test, size/L

#19 Remove dockerhub proxy references
  config/jobs/build-images/build.yaml
  images/dind-go-kubectl/Dockerfile
Labels: size/XS, lgtm, approved

#20 Add testgrid config for test-prow postsubmit job
  config/jobs/test-prow/test.yaml
Labels: size/XS, lgtm, approved

#21 Add testgrid config for test images job and rename periodic job
  config/jobs/build-images/build.yaml
Labels: size/XS, lgtm, approved

#22 Add testgrid config for periodic image job
  config/jobs/build-images/build.yaml
Labels: size/XS, lgtm, approved

#23 Add testgrid configs
  config/testgrid/config.yaml
  config/testgrid/default.yaml
  config/testgrid/namespace.yaml
  config/testgrid/summarizer.yaml
  config/testgrid/updater.yaml
Labels: lgtm, approved, size/L
