Repository vagator/test-infra, pull requests merged in 2022-02, with the labels that each got.

#24 Update test job to test the new cluster
  config/jobs/test-prow/test.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#25 Update test.yaml
  config/jobs/test-prow/test.yaml
Labels: size/XS, approved

#26 Add external secrets
  config/prow/external-secrets.yaml
Labels: lgtm, approved, size/S

#27 s/user/username and namespace the secrets
  config/prow/external-secrets.yaml
Labels: size/XS, lgtm, approved

#28 Add debian based dind image and push to registry
  config/jobs/build-images/build-push-base.yaml
  images/base/Dockerfile
  images/base/dockerd-entrypoint.sh
  scripts/ci-docker-build-image.sh
Labels: lgtm, approved, size/L

#30 Fix base job
  config/jobs/build-images/build-push-base.yaml
Labels: size/XS, lgtm, approved

#31 Change the cluster to test-jobs
  config/jobs/build-images/build-push-base.yaml
Labels: size/XS, lgtm, approved

#34 add postsubmits for test-infra
  config/jobs/test-infra/postsubmits.yaml
Labels: size/XS, approved

#35 execute permissions
  images/base/dockerd-entrypoint.sh
Labels: size/XS, approved

#36 add pod utilities
  config/jobs/test-infra/postsubmits.yaml
Labels: size/XS, lgtm, approved

#38 Fix postsubmit job
  config/jobs/test-infra/postsubmits.yaml
Labels: size/XS, lgtm, approved

#39 Fix error in base Dockerfile
  images/base/Dockerfile
Labels: size/XS, lgtm, approved

#40 fix base image build job
  scripts/ci-docker-build-image.sh
Labels: size/XS, lgtm, approved

#41 Create README.md
  images/base/README.md
Labels: size/XS, lgtm, approved

#42 fix base build job
  images/base/Dockerfile
  images/base/dockerd-entrypoint.sh
  scripts/ci-docker-build-image.sh
Labels: lgtm, approved, size/M

#43 Update README.md
  images/base/README.md
Labels: size/XS, lgtm, approved
