Repository vagator/test-infra, pull requests merged in 2022-03, with the labels that each got.

#45 Refactor image-builder image and prowjob
  config/jobs/test-infra/postsubmits.yaml
  config/prow/config.yaml
  images/base/README.md
  images/image-builder/Dockerfile
  images/image-builder/README.md
  images/image-builder/entrypoint.sh
  images/image-builder/run.sh
  scripts/ci-docker-build-image.sh
Labels: lgtm, approved, size/L

#46 Update README of image-builder
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#48 trigger for image-builder job
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#49 Fix image-builder Dockerfile
  config/jobs/test-infra/postsubmits.yaml
  images/image-builder/Dockerfile
  images/image-builder/run.sh
Labels: size/XS, lgtm, approved

#50 Trigger for image-builder job
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#51 add aws credentials as secrets to image-builder job
  config/jobs/test-infra/postsubmits.yaml
  config/prow/config.yaml
Labels: lgtm, approved, size/S

#53 Trigger for image-builder job
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#54 Fix error in image-builder
  config/jobs/test-infra/postsubmits.yaml
  images/image-builder/run.sh
Labels: size/XS, lgtm, approved

#55 Trigger for image-builder job
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#56 Trigger for image-builder job
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#57 update image-builder job
  config/jobs/test-infra/postsubmits.yaml
  images/image-builder/Dockerfile
  images/image-builder/run.sh
Labels: size/XS, lgtm, approved

#58 Trigger for image-builder job
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#59 fix aws command in image-builder
  config/jobs/test-infra/postsubmits.yaml
  images/image-builder/run.sh
Labels: size/XS, lgtm, approved

#60 Trigger for image-builder job
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#61 fix image builder job
  config/jobs/test-infra/postsubmits.yaml
  images/image-builder/run.sh
Labels: size/XS, lgtm, approved

#62 debug image builder
  images/image-builder/run.sh
Labels: size/XS, lgtm, approved

#63 debug image builder
  images/image-builder/run.sh
Labels: size/XS, lgtm, approved

#64 update image builder
  config/jobs/test-infra/postsubmits.yaml
Labels: size/XS, lgtm, approved

#65 Trigger for image-builder job
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#66 debug image-builder
  config/prow/config.yaml
Labels: size/XS, lgtm, approved

#67 Trigger for image-builder job
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#68 debug image-builder
  config/prow/config.yaml
Labels: size/XS, lgtm, approved

#69 Trigger for image-builder job
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#70 Add error handling and testgrid config for image-builder
  config/jobs/test-infra/postsubmits.yaml
  config/testgrid/config.yaml
  images/image-builder/run.sh
Labels: lgtm, approved, size/S

#71 Optimize image-builder
  images/image-builder/Dockerfile
  images/image-builder/run.sh
Labels: lgtm, approved, size/S

#72 Fix issue with image-builder
  images/image-builder/run.sh
Labels: size/XS, lgtm, approved

#74 debug image-builder
  config/jobs/test-infra/postsubmits.yaml
Labels: size/XS, lgtm, approved

#75 Trigger for image-builder job
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#76 Add AWS creds back to get around token expiration
  images/image-builder/Dockerfile
  images/image-builder/run.sh
Labels: size/XS, lgtm, approved

#77 Fix login to ECR
  images/image-builder/run.sh
Labels: size/XS, lgtm, approved

#78 Add region us-east-1 to get-login-password for ECR
  images/image-builder/run.sh
Labels: size/XS, lgtm, approved

#79 Fix aws creds in run.sh
  images/image-builder/run.sh
Labels: size/XS, lgtm, approved

#80 Fix secrets for AWS creds
  config/prow/config.yaml
Labels: size/XS, lgtm, approved

#81 Trigger for image-builder
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#82 Add test-image
  config/jobs/test-infra/postsubmits.yaml
  images/test-image/Dockerfile
  images/test-image/entrypoint.sh
  images/test-image/run.sh
Labels: lgtm, approved, size/M

#83 Trigger for test-image
  images/test-image/README.md
Labels: size/XS, lgtm, approved

#84 Trigger for test-image
  images/test-image/README.md
Labels: size/XS, lgtm, approved

#85 Add Periodic job to build and test TCE
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/S

#86 Add test job to trigger
  config/jobs/test-prow/test.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#88 Modularize image-builder
  images/image-builder/Dockerfile
  images/image-builder/dind.sh
  images/image-builder/run.sh
Labels: lgtm, approved, size/L

#89 Fix image-builder job
  config/jobs/test-infra/postsubmits.yaml
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#90 Fix image-builder job
  config/jobs/test-infra/postsubmits.yaml
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#91 Trigger for image-builder
  images/image-builder/README.md
Labels: size/XS, lgtm, approved

#92 Fix test-image
  config/jobs/test-infra/postsubmits.yaml
  images/test-image/Dockerfile
  images/test-image/run.sh
Labels: lgtm, approved, size/S

#93 Trigger for test-image
  images/test-image/README.md
Labels: size/XS, lgtm, approved

#94 Fix TCE periodic job
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved

#96 Fix TCE job and change cadence to every hour
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved

#97 Fix TCE periodic job
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved

#98 add boskos to prow
  config/prow/boskos/README.md
  config/prow/boskos/boskos-resources.yaml
  config/prow/boskos/cleaner.yaml
  config/prow/boskos/crd.yaml
  config/prow/boskos/janitor.yaml
  config/prow/boskos/kustomization.yaml
  config/prow/boskos/namespace.yaml
  config/prow/boskos/patch-aws-account/job.yaml
  config/prow/boskos/patch-aws-account/rbac.yaml
  config/prow/boskos/rbac.yaml
  config/prow/boskos/reaper.yaml
  config/prow/boskos/resource-configmap.yaml
Labels: lgtm, approved, needs-ok-to-test, size/XL

#99 Change TCE build job interval to 24h
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved

#100 Add kubernetes-external-secrets
  config/kubernetes-external-secrets_crd.yaml
  config/kubernetes-external-secrets_deployment.yaml
  config/kubernetes-external-secrets_rbac.yaml
  config/kubernetes-external-secrets_sa.yaml
  config/kubernetes-external-secrets_service.yaml
Labels: lgtm, approved, size/L

#101 move kes yamls to config/prow
  config/prow/kubernetes-external-secrets_crd.yaml
  config/prow/kubernetes-external-secrets_deployment.yaml
  config/prow/kubernetes-external-secrets_rbac.yaml
  config/prow/kubernetes-external-secrets_sa.yaml
  config/prow/kubernetes-external-secrets_service.yaml
Labels: size/XS, lgtm, approved

#102 add boskos python script to test-image Dockerfile
  config/prow/config.yaml
  images/test-image/Dockerfile
  images/test-image/boskos.py
Labels: lgtm, approved, needs-ok-to-test, size/L

#103 test tce boskos integration
  config/jobs/tce/periodics.yaml
  images/test-image/Dockerfile
Labels: lgtm, approved, needs-ok-to-test, size/M

#104 test trigger: change cron schedule to every 30 min
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#107 test trigger: update test-image sha
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#108 move test boskos job to 24 hours interval
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#109 test trigger on personal TCE fork
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#110 trigger to test boskos acquire, heartbeat & release account
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, needs-ok-to-test

#111 fix tce/periodics.yaml for boskos commands
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, needs-ok-to-test

#112 fix tce/periodics.yaml for boskos commands -2
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#113 move tce-bosks test job to test-jobs build cluster
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#114 renaming periodic to trigger again, previous one stuck in pending
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#115 move tce boskos test job to 24 hr interval
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, needs-ok-to-test

#116 add WIP periodics-fetch-tce job
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, needs-ok-to-test, size/M

#117 trigger for tce-test periodic job
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, needs-ok-to-test

#118 fix tce test job permission denied error
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, needs-ok-to-test

#119 change interveal to 24h
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#120 part fix for tce+boskos test
  config/jobs/tce/periodics.yaml
  images/test-image/Dockerfile
Labels: size/XS, lgtm, approved, needs-ok-to-test

#122 set 24h interval
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, needs-ok-to-test

#123 modify tce boskos job to fetch tce release, not build
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, needs-ok-to-test

#124 24h interval
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, needs-ok-to-test

#126 Testing the TCE on docker
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/S, needs-ok-to-test

#127 Testing TCE on docker
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#128 Add AWS encoded creds and key-name
  config/prow/config.yaml
  config/prow/external-secrets.yaml
Labels: lgtm, approved, size/M

#129 rerun tce-on-aws job with updated aws-credentials-preset
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved

#131 update aws creds preset env varibale to not use volume mounts
  config/jobs/tce/periodics.yaml
  config/prow/config.yaml
Labels: lgtm, approved, size/M

#132 Changed time interval of TCE docker
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#134 increase interval to every 3h
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved

#135 testing TCE on docker
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#136 move preset env variables to tce-on-aws job definition for testing purpose
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/S

#137 move tce jobs interval to 24h
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved

#138 trigger tce-on-aws job
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved

#139 Update image-builder Dockerfile
  images/image-builder/Dockerfile
Labels: size/XS, lgtm, approved

#140 update base image-builder version tag
  images/test-image/Dockerfile
Labels: size/XS, lgtm, approved

#141 update test-image sha for test-tce-job-aws
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved

#142 change cron schedule to every 3h
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved

#143 Changed the job frequency
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#145 test tce job with krte
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/M

#146 update tce with krel periodic frequency
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved

#147 trigger tce using krel job after part fixes
  config/jobs/tce/periodics.yaml
Labels: size/XS, lgtm, approved
